### ISSUE TITLE
Cannot resolve module 'vue-at'

### ISSUE THREAD

**Issue by antongorodezkiy** [fritx/vue-at#1]
Hello @fritx 

`package.json` is referencing `dist/index.js` - https://github.com/fritx/vue-at/blob/master/package.json#L11 but there is no `dist` directory in the package.

So when requiring it with `require('vue-at')` I got an error:

> Cannot resolve module 'vue-at'

**Comment by fritx** [comment]
Oops! My bad.. I guess I mistakenly ignored `dist/` in .npmignore.
It's weird that I can't find it in the github repo now 😕 
Let me republish it.

**Comment by fritx** [comment]
Even though I republished vue-at@2.0.1 based on files of this repo,
it's terrible there is still an npmignore and no dist/ in the package.

**Comment by antongorodezkiy** [comment]
Could the issue be in https://github.com/fritx/vue-at/blob/master/.gitignore#L3 ?

**Comment by fritx** [comment]
@antongorodezkiy yeah, thank ya so much for reporting this. :+1:
I guess I've figured out what was going on...

**If npmignore is missing, it occurs same as gitignore in the package.**
I didn't check it by `npm pack` before `npm publish` -- my bad.

Once if I put my npmignore (without dist/), it will be the one in the package.
I now highly doubt Is it a new bug or behavior of npm?

2.0.2 is out now with the fix.

**Comment by antongorodezkiy** [comment]
> I now highly doubt Is it a new bug or behavior of npm?

Unfortunately I don't know.

> 2.0.2 is out now with the fix.

Seems to be fixed, thank you!
