### ISSUE TITLE
创建一个@区域，移动滚动条再输入@会导致@弹出层位置计算偏移 BUG

### ISSUE THREAD

**Issue by daomiaru** [fritx/vue-at#126]
正常打开页面不拖动滚动条时，输入@位置计算正确，但是当拖动滚动条时@弹出层的位置就变了。大佬可不可以看一下

**Comment by fritx** [comment]
@daomiaru hi，抱歉，可否提供你的demo，可能和这个已有的issue有关 https://github.com/fritx/vue-at/issues/10

**Comment by daomiaru** [comment]
哇，谢谢大佬的回复。一下是demo代码
<template>
	<div>
		<div style="height: 300px;">
			
		</div>
		  <at :members="members" name-key="name">
		    <template slot="item" slot-scope="s">
		      <img :src="s.item.avatar">
		      <span v-text="s.item.name"></span>
		    </template>
		    <div class="editor"  contenteditable></div>
		  </at>
	</div>
</template>

<script>
	import At from 'vue-at'
	export default{
		components: { At },
		data(){
			return{
				members: [{
				  avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
				  name: 'myrtie.green'
				}, {
				  avatar: 'https://randomuser.me/api/portraits/men/8.jpg',
				  name: '椿木'
				}]
			}
		}
	}
</script>

<style lang="scss">
	.editor {
	  width: 400px;
	  height: 200px;
	  overflow: auto;
	  white-space: pre-wrap;
	  border: solid 2px rgba(0,0,0,.5);
	}
	/* override styles */
	#app .atwho-li {
	  padding: 0 4px;
	}
	#app .atwho-li img {
	  height: 100%;
	  width: auto;
	  -webkit-transform: scale(.8);
	}
	#app .atwho-li span {
	  padding-left: 8px;
	}
	#app .atwho-wrap {
	  display: inline-block;
	  vertical-align: top;
	  margin-left: 40px;
	  margin-top: 30px;
	}
</style>

**Comment by daomiaru** [comment]
![Uploading QQ截图20201018211648.png…]()

**Comment by daomiaru** [comment]
![QQ截图20201018211648](https://user-images.githubusercontent.com/52020723/96368642-6ed78b00-1144-11eb-9725-b8c9aea9e8bb.png)

**Comment by daomiaru** [comment]
![Uploading QQ截图20201018211808.png…]()

**Comment by daomiaru** [comment]
![QQ截图20201018211808](https://user-images.githubusercontent.com/52020723/96368649-81ea5b00-1144-11eb-82d2-73fb45306214.png)

**Comment by daomiaru** [comment]
![QQ截图20201018211648](https://user-images.githubusercontent.com/52020723/96368653-8f074a00-1144-11eb-9b46-09bb4796563d.png)

**Comment by daomiaru** [comment]
插件下载是这个npm i vue-at@2.x  # for Vue2。

**Comment by daomiaru** [comment]
代码
<template>
	<div>
		<div style="height: 300px;">
			
		</div>
		  <at :members="members" name-key="name">
		    <template slot="item" slot-scope="s">
		      <img :src="s.item.avatar">
		      <span v-text="s.item.name"></span>
		    </template>
		    <div class="editor"  contenteditable></div>
		  </at>
		  <div style="height: 1000px;"></div>
	</div>
</template>

<script>
	import At from 'vue-at'
	export default{
		components: { At },
		data(){
			return{
				members: [{
				  avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
				  name: 'myrtie.green'
				}, {
				  avatar: 'https://randomuser.me/api/portraits/men/8.jpg',
				  name: '椿木'
				}]
			}
		}
	}
</script>

<style lang="scss">
	.editor {
	  width: 400px;
	  height: 200px;
	  overflow: auto;
	  white-space: pre-wrap;
	  border: solid 2px rgba(0,0,0,.5);
	}
	/* override styles */
	#app .atwho-li {
	  padding: 0 4px;
	}
	#app .atwho-li img {
	  height: 100%;
	  width: auto;
	  -webkit-transform: scale(.8);
	}
	#app .atwho-li span {
	  padding-left: 8px;
	}
	#app .atwho-wrap {
	  display: inline-block;
	  vertical-align: top;
	  margin-left: 40px;
	  margin-top: 30px;
	}
</style>

**Comment by daomiaru** [comment]
老哥我看了一下好像是我现在用的这个框架可能是设置了什么css的原因导致浏览器滚动事件包括window.pageYOffset都失效了导致弹出层位置偏移。我把框架的地址给你你可以帮我看看该怎么改吗 https://gitee.com/smallc/Saber. 麻烦大佬了

**Comment by daomiaru** [comment]
解决了谢谢大哥

**Comment by KingOneYan** [comment]
@daomiaru 兄弟，我也遇到了一摸一样的问题，能否请教一下怎么解决

**Comment by daomiaru** [comment]
> @daomiaru 兄弟，我也遇到了一摸一样的问题，能否请教一下怎么解决

源码中有个scrollRef属性，你f12审查元素查看滚动条是哪个，把这个滚动条传入就行了
![QQ截图20201022141826](https://user-images.githubusercontent.com/52020723/96832564-8a5ad280-1471-11eb-9fbf-0f3cbd8b3356.png)

**Comment by KingOneYan** [comment]
> > @daomiaru 兄弟，我也遇到了一摸一样的问题，能否请教一下怎么解决
> 
> 源码中有个scrollRef属性，你f12审查元素查看滚动条是哪个，把这个滚动条传入就行了
> ![QQ截图20201022141826](https://user-images.githubusercontent.com/52020723/96832564-8a5ad280-1471-11eb-9fbf-0f3cbd8b3356.png)

没能理解，是传入滚动条对应的元素的类名吗，还是应该说传对应的ref，但是我目前使用的是封装好的富文本，里面内容滚动条拿不到对应的ref，我目前传className不起作用

**Comment by daomiaru** [comment]
> > > @daomiaru 兄弟，我也遇到了一摸一样的问题，能否请教一下怎么解决
> > 
> > 
> > 源码中有个scrollRef属性，你f12审查元素查看滚动条是哪个，把这个滚动条传入就行了
> > ![QQ截图20201022141826](https://user-images.githubusercontent.com/52020723/96832564-8a5ad280-1471-11eb-9fbf-0f3cbd8b3356.png)
> 
> 没能理解，是传入滚动条对应的元素的类名吗，还是应该说传对应的ref，但是我目前使用的是封装好的富文本，里面内容滚动条拿不到对应的ref，我目前传className不起作用


![QQ截图20201022143355](https://user-images.githubusercontent.com/52020723/96833933-be36f780-1473-11eb-8712-8d3db8bc19bf.png)

**Comment by KingOneYan** [comment]
@daomiaru 没能理解，是传入滚动条对应的元素的类名吗，还是应该说传对应的ref，但是我目前使用的是封装好的富文本，里面内容滚动条拿不到对应的ref，我目前传className不起作用

**Comment by daomiaru** [comment]
> > > > @daomiaru 兄弟，我也遇到了一摸一样的问题，能否请教一下怎么解决
> > > 
> > > 
> > > 源码中有个scrollRef属性，你f12审查元素查看滚动条是哪个，把这个滚动条传入就行了
> > > ![QQ截图20201022141826](https://user-images.githubusercontent.com/52020723/96832564-8a5ad280-1471-11eb-9fbf-0f3cbd8b3356.png)
> > 
> > 
> > 没能理解，是传入滚动条对应的元素的类名吗，还是应该说传对应的ref，但是我目前使用的是封装好的富文本，里面内容滚动条拿不到对应的ref，我目前传className不起作用
> 
> ![QQ截图20201022143355](https://user-images.githubusercontent.com/52020723/96833933-be36f780-1473-11eb-8712-8d3db8bc19bf.png)

源码部分

**Comment by daomiaru** [comment]
> @daomiaru 没能理解，是传入滚动条对应的元素的类名吗，还是应该说传对应的ref，但是我目前使用的是封装好的富文本，里面内容滚动条拿不到对应的ref，我目前传className不起作用

你截个图吧

**Comment by KingOneYan** [comment]
@daomiaru 当前是这个DOM 结构
![image](https://user-images.githubusercontent.com/69427729/96834367-79f82700-1474-11eb-8e0e-349774f95745.png)
template结构是这样的
![image](https://user-images.githubusercontent.com/69427729/96834400-89777000-1474-11eb-9181-8657fd240733.png)

**Comment by daomiaru** [comment]
> @daomiaru 当前是这个DOM 结构
> ![image](https://user-images.githubusercontent.com/69427729/96834367-79f82700-1474-11eb-8e0e-349774f95745.png)
> template结构是这样的
> ![image](https://user-images.githubusercontent.com/69427729/96834400-89777000-1474-11eb-9181-8657fd240733.png)

老哥你图裂了

**Comment by KingOneYan** [comment]
@daomiaru 
![1](https://user-images.githubusercontent.com/69427729/96834729-16bac480-1475-11eb-9b4a-58592c74e40a.png)
![2](https://user-images.githubusercontent.com/69427729/96834779-2d611b80-1475-11eb-959e-51c021ea8830.png)

**Comment by KingOneYan** [comment]
@daomiaru 老哥，图片不知道为什么怎么样都发不出来了，可以加你QQ私聊吗

**Comment by daomiaru** [comment]
1433149685




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KingOneYan"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 下午2:46
收件人: "fritx/vue-at"<vue-at@noreply.github.com&gt;; 
抄送: "中分痞子莫扎特"<1433149685@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [fritx/vue-at] 创建一个@区域，移动滚动条再输入@会导致@弹出层位置计算偏移 BUG (#126)





 
@daomiaru 老哥，图片不知道为什么怎么样都发不出来了，可以加你QQ私聊吗
