### ISSUE TITLE
can not get v-model value

### ISSUE THREAD

**Issue by 15926524** [fritx/vue-at#149]
Hello, 
I'm using vue-at with Quasar framework with vue and vue-at versions bellow:
- vue: 3.0.0,
- vue-at: 3.0.0-alpha.2

but i cannot get the v-model value with this code:

```vue
<template>
  <at :members="members" v-model="atText">
    <div :contenteditable="true"></div>
  </at>
  <at-ta :members="members" v-model="atTaText">
    <textarea v-model="textA"></textarea>
  </at-ta>
  <p>{{ members }}</p>
  <p>{{ atText }}</p>         // ← Never changed TODO:
  <p>{{ atTaText }}</p>       // ← Never changed TODO:
  <p>{{ textA }}</p>          // ← will change TODO:
</template>

<script>
import At from 'vue-at' // for content-editable
import AtTa from 'vue-at/dist/vue-at-textarea' // for textarea

export default {
  components: { At, AtTa },
  data () {
    return {
      members: ['Roxie Miles', 'grace.carroll', 'Allen'],
      atText: "atat",
      atTaText:"tata",
      textA:"textA"
    }
  }
}
</script>
```

can you give me any suggestions? Thanks!

**Comment by 15926524** [comment]
I realized I used the wrong syntax. I should have used `v-model:value`. The corrisponde example is in the branch "wip-vue3", file "app.vue".


ps. can u update the project documentation?  I noticed that the project documentation is still the vue2 version, or at least can u mark the version used in the documentation? Thanks!

**Comment by fritx** [comment]
@15926524 you are right, the current entry of vue3 documentation is not obvious, which needs to be improved.

> for Vue3, read [this one](https://github.com/fritx/vue-at/tree/vue3#readme) instead.

![image](https://github.com/fritx/vue-at/assets/6647633/84e56d06-2e98-4f0f-afda-5a7f598445f8)

**Comment by fritx** [comment]
Also see: https://github.com/fritx/vue-at/issues/148#issuecomment-1508169864

For Quasar q-input, this should work:

```html
<at-ta :members="members">
  <q-input
    v-model="name"
    type="textarea"
    :rows="1"
    :autogrow="false"
    resize="none"
  />
</at-ta>
```
