### ISSUE TITLE
触发词只能是@吗？

### ISSUE THREAD

**Issue by caoxiaoshuai1** [fritx/vue-at#19]
没有找到触发词修改的地方，需要修改源码再打包吗？

**Comment by fritx** [comment]
哦，不用，目前文档不是很详细。
后来有人加上了这个功能 - https://github.com/fritx/vue-at/pull/17

可以试一下这样：

```vue
<at at="~"></at>
<at :ats="['@', '~']"></at>
```

**Comment by fritx** [comment]
关于 props `at`, `ats` 的文档链接：
https://fritx.github.io/vue-at/#/en/propsats
