### ISSUE TITLE
Members' List not Showing When the Script is Built

### ISSUE THREAD

**Issue by pingshunhuangalex** [fritx/vue-at#21]
Hi @fritx 

Thanks for the amazing package there.

I'm using Vue-at with textarea, and everything works fine in `npm run dev` server. However, when I build my project using `npm run build` (no error threw out), the members' list just becomes invisible. The DOM still gets rendered and using arrow keys and enter can still autocomplete the members without any problem, but the list just not there after I type `@`.

Meanwhile, if you check the example in your own doc (https://fritx.github.io/vue-at/#/en/textarea), something is definitely wrong there. Thanks.

**Comment by fritx** [comment]
@pingshunhuangalex yes, sorry about that.

Actually I had noticed that but didn't fix it yet.
I guess it was a bug included by a recent commit of mine: https://github.com/fritx/vue-at/commit/86c1040e4d3ae2926a6e48a43bbf10f5acde9ee6

**Comment by pingshunhuangalex** [comment]
On second thought, the position misplacement in doc may not be the same as my issue. My issue is more like the list not showing at all when the project is built, but if I inspect the elements, things seem to be in the right place. It's just not showing up.

Any guesses or direction to check would be greatly appreciated. Thanks.

**Comment by fritx** [comment]
@pingshunhuangalex oh that's weird.
Is there a scrollbar inside your textarea?
Would it help by adjusting `z-index`?

**Comment by pingshunhuangalex** [comment]
@fritx I changed the text area to a single line "input" thing. I tried, z-index, opacity, visibility, display, etc. None of them works. The weirdest thing is everything works in dev server, but things just disappear after building. (I'm using Vue-cli)

**Comment by pingshunhuangalex** [comment]
Hi @fritx 
I tried again today with a standalone simple Vue component, and it seems the issue is reproducible. Could you please have a look if anything changes in the script that makes the list invisible after building the script using Vue-CLI's setting? Thanks.

**Comment by fritx** [comment]
@pingshunhuangalex I'm not sure, but I tried to fix textarea offset bug when scrolling
Try v2.2.4 instead. If there is problem let me know :P

**Comment by pingshunhuangalex** [comment]
Thanks so much @fritx 
The latest update seems to do the trick. Please keep up the good work!

**Comment by fritx** [comment]
Thanks, would try my best xD @pingshunhuangalex
