### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by rap2hpoutre** [fritx/vue-at#39]
Thanks for your package. It could be great if this component could display a placeholder, just like a regular textarea (maybe it's already possible, but I did not found how)

**Comment by fritx** [comment]
@rap2hpoutre thanks for using vue-at also. 😄 
Which one do you use, `div`s or `textarea`s?

**Comment by rap2hpoutre** [comment]
Oops. Sorry! It works with textarea!

**Comment by hamoudchohan** [comment]
@fritx how can we add placeholders with divs

**Comment by fritx** [comment]
@hamoudchohan I created a demo: https://codepen.io/fritx/pen/NZpbqW
-- "Pure-CSS Placeholder for content-editable div"
