### ISSUE TITLE
Add support for input

### ISSUE THREAD

**Issue by rap2hpoutre** [fritx/vue-at#40]
I can use **vue-at** for `div` and `textarea` but not `input`. Do you think it could be possible?

Thanks for your package.

**Comment by fritx** [comment]
But I'm not sure replacing those `querySelector('textarea')` to `'textarea, input'` could solve it, worth a try.

https://github.com/fritx/vue-at/blob/41e40f7e2f1076c2d35c188930f922befd031995/src/AtTextarea.vue#L28

**Comment by fritx** [comment]
@rap2hpoutre btw, could you use `<textarea rows="1">`s instead of `<input>`s?

**Comment by rap2hpoutre** [comment]
@fritx That's what I have done, so it's OK I guess! Thanks!

**Comment by raind33** [comment]
> @rap2hpoutre btw, could you use a `<textarea rows="1" style="resize:none">`
> instead of an `<input>`? Related comment: [#11 (comment)](https://github.com/fritx/vue-at/issues/11#issuecomment-329032102)

now cound it support input?
