### ISSUE TITLE
Is there a way to handle a change?

### ISSUE THREAD

**Issue by goldsteinr** [fritx/vue-at#49]
I would like to handle a change with a specific value for the user mentioned.

Example:

```html
 <at-ta :members="members" name-key="email" @change="handleChante(s.item.email)" v-model="commentForm.comment">
    <template slot="item" slot-scope="s">
        <img :src="s.item.thumb">
        <span v-text="`${s.item.firstName} ${s.item.lastName}`"></span>
    </template>
    <textarea class="editor" rows="1" :disabled="getIsLoading" placeholder="Type here a message, question, information..."></textarea>
 </at-ta>
```

Is this possible?

**Comment by goldsteinr** [comment]
added in #50

**Comment by fritx** [comment]
@goldsteinr you mean you need access to the very member-item on the event `@at`?

**Comment by Ashirogi-Muto** [comment]
Is this feature available in the latest release?

**Comment by fritx** [comment]
@Ashirogi-Muto sorry that I removed `@at memberObj` in favor of `@insert`
https://github.com/fritx/vue-at/commit/06f0deff539a101f5111183fa833c24846817b51

> @at events were always broken, need to be fixed
