### ISSUE TITLE
How to remove the suggestions on already selected values on page load

### ISSUE THREAD

**Issue by stacybot123** [fritx/vue-at#64]
Hi,

Thank you guys for putting efforts on creating this awesome plugin. This works great. I have only one problem. Whenever I reload the page it highlights all already selected values on the screen. I want to remove those so they will appear only when the textarea is selected or the field is selected
Please check below image 

![image](https://user-images.githubusercontent.com/26300235/40973086-886a359a-68e0-11e8-8b0e-a567fa8d7e76.png)

**Comment by fritx** [comment]
![image](https://user-images.githubusercontent.com/6647633/41193379-8fa71a16-6c3d-11e8-8d3a-c1dc9ae18083.png)

Ah, Github has the same behavior too, which could make sense! It gives us the user a chance to press enter and get the necessary trailing space appended without manually adding it! xD

I added a prop `showUnique(=true/false)` and tested like the following (a little weird code):

```diff
     const name = itemName(v)
     return filterMatch(name, chunk, at)
   })

+  show = false
   if (matched.length) {
+    show = true
+    if (!showUnique) {
+      let item = matched[0]
+      if (chunk === itemName(item)) {
+        show = false
+      }
+    }
+  }

+  if (show) {
     this.openPanel(matched, range, index, at)
   } else {
     this.closePanel()
```

Any thoughts? Better naming or logic and PR is welcomed :D

**Comment by stacybot123** [comment]
@fritx  Sorry for the late reply. Yes, I tried the code you provided above, but it doesn't seems to resolve the issue. Maybe I am messing something up on recompiling the modules.

**Comment by stacybot123** [comment]
@fritx can you let me know the steps so I can resolve this. I am new to vue js and node . Can't figure it out . Should I open a PR request to add this feature? Thanks!

**Comment by stacybot123** [comment]
Resolved issue . thanks!!

**Comment by fritx** [comment]
Sorry that I hadn't merged that branch yet before.
If I confirm the branch is ok I would merge it xD
How did you solve that?

**Comment by stacybot123** [comment]
@fritx  Yes, I am waiting on that release.  I did tried above code but it did't worked. I added timeout on page load and set the at keyword 10 seconds after the page loads. That temporally  resolved the issue.

Sorry for the delay in replying
