### ISSUE TITLE
Clicking suggested item removes prefix

### ISSUE THREAD

**Issue by Wulthan** [fritx/vue-at#67]
Using following code works fine until I click a suggested item instead of selecting it with ENTER

```javascript
import AtTextarea from 'vue-at/dist/vue-at-textarea'
```
```html
<at-textarea at="$" suffix="$ " :members="members">
            <text-area class="text-input"/>
</at-textarea>
```
```javascript
members: ["John", "Ben"]
```

Using ENTER to select an item I get following example output:
`$John$ `

But when I select the member using a mouse click this output ends up in my text area:
`John$`

For some reason it removes my "at" -Character and I can't figure out why.

**Update:**
I just figured out that not only the "at"-Character is removed, everything before is removed:
`Foo bar` turns into `John$` instead of the expected `Foo bar $John$`

**Comment by Wulthan** [comment]
@fritx Sorry for the late response. It was an internal issue and is fixed now.

**Comment by fritx** [comment]
@Wulthan cool, btw, what kind of internal issue?

**Comment by Wulthan** [comment]
@fritx Our drawing framework bugged out with the letter "$" in textfields. Fixing that allowed the textarea to behave like expected. So it was nothing on your side.
