### ISSUE TITLE
the letter before ‘@’ must be space?

### ISSUE THREAD

**Issue by KuiShang** [fritx/vue-at#7]
the letter before ‘@’ must be space? it can't work like this 'ex:  abc@'. must 'abc @'

**Comment by fritx** [comment]
@KuiShang hi, sorry for the missing docs.
You can try this one:

```vue
<at :avoid-email="false"></at>
```

https://github.com/fritx/vue-at/blob/3cc035f7f117f223d1afe11e2ceb2f90ce72049d/src/At.vue#L51
According to the source code, there are some props defined.
The prop avoidEmail is true by default.

https://github.com/fritx/vue-at/blob/3cc035f7f117f223d1afe11e2ceb2f90ce72049d/src/At.vue#L209
If it is on, it will not allow `/^[a-z0-9]$/i` as the letter before `@`.

**Comment by fritx** [comment]
Docs of props `at`, `ats` is here:
https://fritx.github.io/vue-at/#/en/propsats
