### ISSUE TITLE
Mobile > Cannot delete embedded item

### ISSUE THREAD

**Issue by freitasskeeled** [fritx/vue-at#73]
Hi,

I use `vue-at` with a custom `embeddedItem` and on **desktop** it works fine. If I try on **mobile**, I cannot delete it. It adds what seems to be characters from the end of the custom `embeddedItem` and if I try to select the whole element the keyboard disappears.

I'm using the latest version: 2.5.0-beta

Thanks.

**Comment by fritx** [comment]
Hi @freitasskeeled , did you solve the problem?
