### ISSUE TITLE
@插入span元素后,无法使用键盘左右按钮移动光标跨过span

### ISSUE THREAD

**Issue by yeli19950109** [fritx/vue-at#84]
```
<span slot="embeddedItem" slot-scope="s">
    <span :id="s.current.id">@{{ s.current.name }}</span>
</span>
```
![image](https://user-images.githubusercontent.com/22110692/50875649-516c7d80-1404-11e9-8384-ec7b9d473650.png)

用鼠标点击更换光标位置之后  , 按向左或向右的都会在遇到 contenteditable=false的span处 停住  无法跨越这个标签
浏览器 chrome

**Comment by yeli19950109** [comment]
编辑器是用的 medium-editor

**Comment by fritx** [comment]
@yeli19950109 有没有添加这样的css样式：

```css
.my-editor {
  white-space: pre-wrap; 
}
```

https://github.com/fritx/vue-at/issues/74#issuecomment-433898638
https://github.com/fritx/vue-at/issues/82#issuecomment-450051605
