### ISSUE TITLE
Get Current Tags

### ISSUE THREAD

**Issue by DevHossamAli** [fritx/vue-at#92]
### **Could you add a functionality for getting the current added tags as members?**
![image](https://user-images.githubusercontent.com/20017341/54142072-95ddbf00-442f-11e9-95fd-c8be3531c1bf.png)

```
current_tagged_members: 
[{
  name: "John",
  id: "123456"
},
{
  name: "Jen",
  id: "987654"
}]
```

**Comment by fritx** [comment]
Hi, it is related to #34, but again

It's hard to get the complete tagInfo like `{ name, id }`, I think.

‘Cause if the html content was put from server as direct string field in response like

```js
response = { atInput: '<em>@John</em> <em>@Jen</em> test comment' }
```

then `<at>` would be not able to detect what the hole tagInfo was.

**Comment by DevHossamAli** [comment]
Ok thanks
