### ISSUE TITLE
Mention Dropdown remain open for Textarea

### ISSUE THREAD

**Issue by arifhussain353** [fritx/vue-at#93]
For `Textarea` :
 if i add `@` at the start and remove it. Then mention dropdown remain open until i write something again. But this issue never come up with `div` tag `Contenteditable`.
Is there any option hide dropdown for empty the textarea  after write once?
Someone already discussed [here](https://github.com/fritx/vue-at/issues/79#issuecomment-444080098)
Is there any update for fix this issue?
[demo link](https://fritx.github.io/vue-at/#/en/textarea)
Browser : `Chrome Version 71.0.3578.98 (Official Build) (64-bit)`

**Comment by fritx** [comment]
@arifhussain353 yeah the demo link did reproduce the bug to me, thanks

**Comment by arifhussain353** [comment]
@fritx  will wait for the fix. Good luck :+1:

**Comment by fritx** [comment]
@arifhussain353 try the latest version plz, can not reproduce it by the App.vue though

**Comment by arifhussain353** [comment]
@fritx  ok Thank you. I will try again.

**Comment by fritx** [comment]
try >= 2.5.0-beta.2
